  services:
    - type: web
      name: crochemama-ig-bot
      env: python
      buildCommand: |
        python3.11 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
      startCommand: "venv/bin/python insta_bot.py"
      envVars:
        - key: PYTHONUNBUFFERED
          value: 1
        - key: PYTHON_VERSION
          value: 3.11.9
      regions:
        - oregon
      plan: free
      autoDeploy: true
